# Google Cloud Run Service Configuration
# This file defines the Cloud Run service configuration
# Deploy with: gcloud run services replace cloudrun-service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: task-manager-mcp
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'

        # CPU allocation
        run.googleapis.com/cpu-throttling: 'true'

        # Startup probe
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: PROJECT_NUMBER-compute@developer.gserviceaccount.com

      containers:
      - name: task-manager-mcp
        image: gcr.io/PROJECT_ID/task-manager-mcp:latest

        ports:
        - name: http1
          containerPort: 8000

        env:
        # Application settings
        - name: DEBUG
          value: "false"
        - name: LOG_LEVEL
          value: "INFO"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "8000"

        # Database (use Cloud SQL or managed PostgreSQL)
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-url
              key: latest

        # OAuth configuration
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: google-client-id
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: google-client-secret
              key: latest
        - name: OAUTH_REDIRECT_URI
          value: "https://task-manager-mcp-PROJECT_ID.a.run.app/oauth/callback"

        # Security
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-key
              key: latest
        - name: ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: encryption-key
              key: latest
        - name: DEVELOPMENT_MODE
          value: "false"

        resources:
          limits:
            cpu: '1000m'
            memory: 512Mi

        startupProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 3
          failureThreshold: 10

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 0
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3

  traffic:
  - percent: 100
    latestRevision: true
